services:
  ppsnr.server:
    image: ppsnr.server
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - ASPNETCORE_URLS=http://+:5271
    ports:
      - "5271"
    build:
      context: .
      dockerfile: PPSNR.Server/Dockerfile

